import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";
import PostContextProvider from "@/app/context/posts/postContextProvider";

const titillium_web = Titillium_Web({ weight: ["200"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={titillium_web.className}>
        <PostContextProvider>{children}</PostContextProvider>
      </body>
    </html>
  );
}
